ALTER TABLE "acca_legs" ALTER COLUMN "scheduled_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "acca_runs" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "acca_runs" ALTER COLUMN "settled_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "accounts" ALTER COLUMN "health_updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "accounts" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "alerts_inbox" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "alerts_inbox" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "alerts_inbox" ALTER COLUMN "read_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_transactions" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_transactions" ALTER COLUMN "confirmed_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "bet_builder_runs" ALTER COLUMN "scheduled_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "bet_builder_runs" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "bet_builder_runs" ALTER COLUMN "settled_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "bets" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "bets" ALTER COLUMN "settled_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "boost_diary" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "boost_diary" ALTER COLUMN "settled_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "casino_games" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "casino_offer_components" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "casino_offer_series" ALTER COLUMN "template_expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "casino_offer_series" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "casino_offer_series" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "casino_offer_series_components" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "casino_offers" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "casino_offers" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "casino_offers" ALTER COLUMN "completed_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "start_time" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "sim_started_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "exchanges" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "feedback_reports" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "history" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "mug_plans" ALTER COLUMN "last_mug_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "mug_plans" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "offer_effort_samples" ALTER COLUMN "started_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "offer_effort_samples" ALTER COLUMN "ended_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "offer_effort_samples" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "offer_ev_snapshots" ALTER COLUMN "locked_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "offer_ev_snapshots" ALTER COLUMN "settled_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "offer_series" ALTER COLUMN "template_expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "offer_series" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "offer_series" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "offers" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "offers" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "offers" ALTER COLUMN "completed_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "push_subscriptions" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "push_subscriptions" ALTER COLUMN "last_ok_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "racing_odds_overrides" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "racing_odds_snapshots" ALTER COLUMN "captured_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "system_legs" ALTER COLUMN "scheduled_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "system_runs" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "system_runs" ALTER COLUMN "settled_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "user_reminders" ALTER COLUMN "remind_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "user_reminders" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "user_reminders" ALTER COLUMN "fired_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "user_reminders" ALTER COLUMN "cancelled_at" SET DATA TYPE bigint;
